import Head from 'next/head'
import Main from './Main'


export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>iSystem</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
     
    <Main />
    </div>
  )

  
}

